[tool.poetry]
name = "pathway"
version = "0.1.0"
description = ""
authors = ["Younes Jaaidi <yjaaidi@gmail.com>"]
packages = [
  { include = "pathway", from = "src" }
]

[tool.poetry.scripts]
start = "pathway.main:main"

[tool.poetry.dependencies]
python = "~3.10"
Rx = "^3.2.0"
numpy = "^1.23.1"
keras = "^2.9.0"
Pillow = "^9.2.0"
scipy = "^1.8.1"
h5py = "^3.7.0"
matplotlib = "^3.5.2"
opencv-python = "^4.6.0"
keras-resnet = "^0.2.0"
tensorflow = "^2.9.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-watch = "^4.2.0"
mypy = "^0.971"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
mypy_path = "src"